Ft show all info excercise 150397731
andela/wger-prometheus pull request #7
Opened 2017-09-06 21:25 UTC by nelmandela

**#150397731 Show all infos for an exercise**

**What does this PR do?**

Creates a new read-only API endpoint that collects all information of an exercise such as muscles, images & category

**Description of Task to be completed?**

Have the following endpoint working;

*GET  /api/v1/exercise/view/*

**How should this be manually tested?**

* Clone the repo, cd into into it and RUN python manage.py run server ;
* Then open it on localhost & try with different exercises id using this url;
 *localhost:8000/api/v2/exercise/view/?id=exercise_id*

**What are the relevant pivotal tracker stories?**

#150397731

![image](https://user-images.githubusercontent.com/29302970/30135308-f06be4a8-9362-11e7-9e2a-a4aa400bb4d2.png)

2017-09-07 11:05 UTC, ghost requested changes
Good job, I only have a few minor fixes and we can merge.

2017-09-07 11:05 UTC, ghost commented on wger/exercises/api/views.py
> +            t = get_thumbnailer(image_obj.image)
t?? rename the variables to be more meaningful

2017-09-07 11:05 UTC, andela-ik commented on wger/exercises/api/views.py
> +        muscles_secondary = [muscles_secondary.name
good use of list generators

2017-09-07 11:05 UTC, andela-ik commented on wger/exercises/api/views.py
> +        print(exercise.equipment.all())
remove print statements unless needed

2017-09-07 12:12 UTC, nelmandela commented on wger/exercises/api/views.py
> +            t = get_thumbnailer(image_obj.image)
thanks for the observation and suggestions.lets work on that then we update

2017-09-08 05:04 UTC, ghost approved these changes

2017-09-08 05:05 UTC, merged